### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by utzig**
WIP - This fixes building with Mynewt as remote repo and adds initial integration with travis. It might break testing on Zephyr before I have a working setup.

PS: So far travis-ci support is not enabled for this repo but I have a ticket opened.

### CODE REVIEW

**Comment by utzig** [comment]
@nvlsianpu Now travis is enabled and functional. Could you check that this PR does not break testing on Zephyr? Or please send me info on how to set it up, so I can update the CI to run Zephyr as well.

**Comment by nvlsianpu** [comment]
Will check on Monday.

**Comment by nvlsianpu** [comment]
Test on zephyr failed. I try https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/subsys/fs/nffs_fs_api/basic on nrf52840_pca10056. 

To reproduce you need just to get patch form mynewt-nffs to zephyr:
`git diff HEAD~9 src/ inlcude/ >> nffs-travis.patch`
and apply it to the zephyr
'git apply nffs-travis.patch --directory=ext/fs/nffs/`

and then build any nffs tests on path subsys/fs/nffs_fs_api/* as usual, then program it to the board and observe serial output (115200 N) wheter it communicate success.

**Comment by utzig** [comment]
@nvlsianpu A clean Zephyr tree also fails with the same errors for me. I tried checking out and older tree (revision `55ce5510f5fca2cd7cb166ecbc065615d6b4424f`) and it worked. I'll see if I am able to find where it broke.

**Comment by nvlsianpu** [comment]
Rechecked - have now the same result as you had. Revision 55ce55.. is the exact on from bisect? Will investigate the issue on zephyr side.

**Comment by utzig** [comment]
So I did the bisect now, https://github.com/zephyrproject-rtos/zephyr/commit/72c7ded5612870c20a3efc3f36a9688ff85a4418 is the first commit that fails. There's lots of different issues from there to the tip. It starts by just failing with no output at all, then it goes to a long list of build issues because of not enough `RAM` and the HEAD a few days ago which was hanging on unlink test seemed to be a masked error because latest HEAD again has issues with linking because of not enough `RAM`.

**Comment by nvlsianpu** [comment]
Looks like project configuration failure - I've got object dedicated for qemu and nrf52 ot once - this must caused to faliure (to big BSS on nrf5x). Probably this is not nffs isue - will fix tomorrow.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
I open related Zephyr PR :`https://github.com/zephyrproject-rtos/zephyr/pull/12107

Zephyr test are runnable only on qemu_x86 currently. Initially they were also runable on nrf52840 but at some point built image swelled up so much that it cause linking failure - so now they need few correction to be able on nrf52840 (https://github.com/zephyrproject-rtos/zephyr/issues/12065 + source code corrections). Not sure when the test build for nrf52840_pca10056 board was disabled - will try to enable this build again later. But see no obstacles to merge this patch.

**Pull request merged**
